title: testjeff
description: Sharing practical test automation with Python, Behave, VS Code & GitHub Copilot.
theme: jekyll-theme-minimal

# If this is a PROJECT site (not username.github.io), set baseurl:
# baseurl: "/YOUR_REPO_NAME"

logo: /assets/img/logo_compressed.png

# Optional: nicer RSS + SEO (both supported by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
