title: testjeff
description: Sharing practical test automation with Python, Behave, VS Code & GitHub Copilot.
theme: jekyll-theme-minimal

# If this is a PROJECT site (not username.github.io), set baseurl:
# baseurl: "/YOUR_REPO_NAME"

logo: /assets/img/testjeff-web-logo-min.png

# Optional: nicer RSS + SEO (both supported by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Default front matter values
defaults:
  - scope:
      path: ""        # applies to all pages
      type: "pages"
    values:
      layout: sidebar
  - scope:
      path: ""        # applies to all posts
      type: "posts"
    values:
      layout: sidebar
