title: testJeff Blog
logo: /assets/img/logo_compressed.png
author: Jeff
description: Sharing my tech thoughts and updates.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one