title: testjeff
description: Sharing practical test automation with Python, Behave, VS Code & GitHub Copilot.
theme: jekyll-theme-minimal

# If this is a PROJECT site (not username.github.io), set baseurl:
# baseurl: "/YOUR_REPO_NAME"

logo: /assets/img/testjeff-web-logo-min.png

# Plugins (all are GitHub Pages–safe)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination settings
paginate: 10
paginate_path: "/blog/page:num"

# Default front matter values
defaults:
  - scope:
      path: ""        # applies to all pages
      type: "pages"
    values:
      layout: sidebar
  - scope:
      path: ""        # applies to all posts
      type: "posts"
    values:
      layout: post-sidebar   # use new sidebar post layout
